apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: techtrends
    tag: latest
  name: techtrends
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.replicaCount }} 
  selector:
    matchLabels:
      app: techtrends
      tag: latest
  template:
    metadata:
      labels:
        app: techtrends
        tag: latest
    spec:
      containers:
      - image: kaetsmjau/{{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: techtrends
        ports:
          - containerPort: {{ .Values.containerPort }}
            protocol: {{ .Values.service.protocol }}
        livenessProbe:
          httpGet:
            path: {{ .Values.livenessProbe.path }}
            port: {{ .Values.containerPort }}
        readinessProbe:
          httpGet:
            path: {{ .Values.readinessProbe.path }}
            port: {{ .Values.containerPort }}
        resources:
{{ toYaml .Values.resources | indent 12 }}