apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: techtrends
  name: techtrends
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol }}
    # targetPort: {{ .Values.service.targetPort }}
    # Standout Suggestion 3: Helm chart conditionals
    targetPort: {{ .Values.service.targetPort | default .Values.service.port | quote }}
  selector:
    app: techtrends
  type: {{ .Values.service.type }}
